// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtvkA_u-cu2wpz4oivMoWBwlmNJ6yVfGA',
    appId: '1:949141340807:web:998d627b38c88c47942e22',
    messagingSenderId: '949141340807',
    projectId: 'mind-tracker-001',
    authDomain: 'mind-tracker-001.firebaseapp.com',
    storageBucket: 'mind-tracker-001.firebasestorage.app',
    measurementId: 'G-KQQ96Y5JJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKyEL0P6nGI9i7B9OPUupv-G-KcqDLaac',
    appId: '1:949141340807:android:a17a011abfd7fe86942e22',
    messagingSenderId: '949141340807',
    projectId: 'mind-tracker-001',
    storageBucket: 'mind-tracker-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbRBwXBfvT_iek8WYmZsJ0ceIedqQZgYw',
    appId: '1:949141340807:ios:0210a6f1246e179c942e22',
    messagingSenderId: '949141340807',
    projectId: 'mind-tracker-001',
    storageBucket: 'mind-tracker-001.firebasestorage.app',
    iosBundleId: 'com.example.mobEdu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbRBwXBfvT_iek8WYmZsJ0ceIedqQZgYw',
    appId: '1:949141340807:ios:0210a6f1246e179c942e22',
    messagingSenderId: '949141340807',
    projectId: 'mind-tracker-001',
    storageBucket: 'mind-tracker-001.firebasestorage.app',
    iosBundleId: 'com.example.mobEdu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtvkA_u-cu2wpz4oivMoWBwlmNJ6yVfGA',
    appId: '1:949141340807:web:403b60aee73fe2d7942e22',
    messagingSenderId: '949141340807',
    projectId: 'mind-tracker-001',
    authDomain: 'mind-tracker-001.firebaseapp.com',
    storageBucket: 'mind-tracker-001.firebasestorage.app',
    measurementId: 'G-QMJEX8CXYR',
  );
}
